Really, really basic logging
alec-deason/shitty-rogue pull request #11
Opened 2018-10-21 01:36 UTC by alec-deason

2018-10-21 19:34 UTC, efexgee requested changes
Please rename logging variable from SHITTY_LOG to... something.

2018-10-23 01:38 UTC, alec-deason commented
I thought you liked descriptive variable names?

2018-10-23 03:21 UTC, alec-deason commented
Ok, done.

2018-10-23 04:56 UTC, efexgee approved these changes

2018-10-23 04:57 UTC, efexgee commented
Thank you

2018-10-23 05:28 UTC, merged